### PR TITLE
java sdk and example

### PR DESCRIPTION
**Pull request by Nzen**
This adds a [gradle-based](https://gradle.org/install/) sdk project that can create a jar for clients. It likewise adds a gradle-based project with a stub that starts the game.

I recognize that this does not include a github workflow for testing each [with gradle](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle), as I don't have experience with that yet.

While I don't have experience with publishing to maven central (the java equivalent to the npm registry) via github, I have [done so](https://issues.sonatype.org/browse/OSSRH-45993) locally before, in case you want some advice. Sonatype (which runs maven central) has pretty good documentation about how to [publish a jar](https://central.sonatype.org/publish/publish-guide/). I found publishing my gpg key to be the most confusing part, given that they only accept keys from whitelisted servers. 

This set of gradle scripts includes some 'decisions' that are political, rather than technical :

The `settings.gradle` file calls out the project name, which controls the name of the jar each project creates. I used _auto-traffic-control-sdk-java_ and _auto-traffic-control-example-java_.

The group of each project as `dev.jdno` plus atc, to match the [prevailing convention](https://central.sonatype.org/publish/requirements/coordinates/), given that you seem to rent jdno.dev. com.auto-traffic-control would also work, given that you've rented that, too. If you change it, do so on the lines that say _group_ and _Automatic-Module-Name_.

This compiles the jar for java v1.8, which is on maintenance only support, but still has [significant use](https://www.infoq.com/news/2021/07/snyk-jvm-2021/). The use of automatic-module-name is a [bridging technique](https://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html) that simplifies compatibility with later versions of java.

### CODE REVIEW

**Comment by jdno** [comment]
Thanks, @Nzen, this contribution is very much appreciated. <3

I'm "out of the office" right now, but will review and merge the PR early next week. We can then iterate in the main branch if we want to improve anything about the documentation or build process.

**Comment by BR-Nicholas-Prado** [comment]
Does this mean the merge commit needs a signature, too ? I'll see to that after work.

It may be worth calling out the signature requirement in the project's readme about contribution.

**Comment by jdno** [comment]
> Does this mean the merge commit needs a signature, too?

That wasn't my intention, so I've disabled it for now. Sorry about that.

**Comment by jdno** [comment]
Review done, looks good! I'll merge the PR into `main` and will then take a look at publishing and the naming conventions.

Thanks for the contribution, @Nzen! ❤️

**Review by jdno — APPROVED** [review]

**Pull request merged**
