### PR TITLE
Add Python SDK and example

### PR DESCRIPTION
**Pull request by Skinner927**
I'm unsure if you're looking for a Python SDK, but I've spent some time on it and figured I'd at least share.

Please let me know what could be improved. I have not created a workflow because I'm looking for permission first.

### CODE REVIEW

**Comment by jdno** [comment]
Hi @Skinner927, contributions are very much appreciated! Especially new SDKs. Thanks for going through the effort of creating one for Python. 🙂

If you want to give the workflow a shot, check out [`test-sdk.yml`](https://github.com/jdno/auto-traffic-control/blob/main/.github/workflows/test-sdk.yml). Would be great to get the same test in place that is used for the other SDKs. Essentially, run the test server and query the version of the game with the example in `examples/python`.

**Comment by Skinner927** [comment]
Thanks @jdno, just chiming in that I plan to start working on these improvements and update the PR.

I'll admit I have no experience creating workflows on GitHub, but have many years of experience with GitLab pipelines and Jenkins, so it should be a fun learning experience. I'd appreciate on the following review if you could be quite critical of whatever workflow solution I come up with -- it's the best way to learn IMO.

**Comment by Skinner927** [comment]
I'm back from the dead. I believe this workflow will work, but I'm honestly unsure because I can't figure out how to test this manually and/or trigger it on my forked repo.

**Comment by Nzen** [comment]
Add `on: workflow_dispatch` to [your workflow](https://github.com/Nzen/mmfimf/blob/master/.github/workflows/java-sdk.yml) to enable running the workflow via the website. The other [event triggers](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) require the trigger to occur, ex git push.

**Comment by Skinner927** [comment]
Well I sure beat my head against this one. Took me about 4 hours to realize the test server is stripped down and only does version. I was running around trying to figure out why starting a game worked locally on Windows and Linux but not on the test 🤦 

Anyways, I believe this is working now.

Thank you @Nzen for the event triggers info. It seems `workflow_dispatch` might only work on master/main? I ended up just using `push` locally.

**Review by jdno — APPROVED** [review]
Hi @Skinner927!

First of all, sorry for the long delay on the review. Second, thanks a lot for your contribution! 🥳 

You've definitely encountered a few issues here that I want to put in the documentation for other folks in the future. Details about how the tests work and how to test workflows in a fork.

**Pull request merged**
